// Package ginserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ginserver

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ApplicationErrorType.
const (
	AlreadyExists ApplicationErrorType = "Already exists"
	BadRequest    ApplicationErrorType = "Bad request"
	InternalError ApplicationErrorType = "Internal error"
	NotFound      ApplicationErrorType = "Not found"
)

// Defines values for EventABIType.
const (
	EventABITypeEvent EventABIType = "event"
)

// Defines values for OperationStatusPayloadStatus.
const (
	OperationStatusPayloadStatusConfirmed OperationStatusPayloadStatus = "confirmed"
	OperationStatusPayloadStatusFailed    OperationStatusPayloadStatus = "failed"
	OperationStatusPayloadStatusPending   OperationStatusPayloadStatus = "pending"
	OperationStatusPayloadStatusSent      OperationStatusPayloadStatus = "sent"
)

// Defines values for OperationStatusPayloadType.
const (
	OperationStatusPayloadTypeOperationStatus OperationStatusPayloadType = "operation.status"
)

// Defines values for WatcherEventPayloadType.
const (
	WatcherEventPayloadTypeWatcherEvent WatcherEventPayloadType = "watcher.event"
)

// Defines values for WatcherStatusPayloadStatus.
const (
	WatcherStatusPayloadStatusDeleted   WatcherStatusPayloadStatus = "deleted"
	WatcherStatusPayloadStatusDeleting  WatcherStatusPayloadStatus = "deleting"
	WatcherStatusPayloadStatusDeploying WatcherStatusPayloadStatus = "deploying"
	WatcherStatusPayloadStatusFailed    WatcherStatusPayloadStatus = "failed"
	WatcherStatusPayloadStatusPending   WatcherStatusPayloadStatus = "pending"
	WatcherStatusPayloadStatusRemoved   WatcherStatusPayloadStatus = "removed"
)

// Defines values for WatcherStatusPayloadType.
const (
	WatcherStatus WatcherStatusPayloadType = "watcher.status"
)

// Defines values for GetChannelsChannelIdEventsParamsType.
const (
	GetChannelsChannelIdEventsParamsTypeOperationStatus GetChannelsChannelIdEventsParamsType = "operation.status"
	GetChannelsChannelIdEventsParamsTypeWatcherEvent    GetChannelsChannelIdEventsParamsType = "watcher.event"
	GetChannelsChannelIdEventsParamsTypeWatcherStatus   GetChannelsChannelIdEventsParamsType = "watcher.status"
)

// ApplicationError defines model for ApplicationError.
type ApplicationError struct {
	// Message Error message describing the issue
	Message string `json:"message"`

	// Type Error type
	Type ApplicationErrorType `json:"type"`
}

// ApplicationErrorType Error type
type ApplicationErrorType string

// Channel defines model for Channel.
type Channel struct {
	// ChannelId Unique identifier for the channel
	ChannelId openapi_types.UUID `json:"channel_id"`

	// CreatedAt Timestamp of when the channel was created
	CreatedAt int64 `json:"created_at"`

	// Name Name of the channel
	Name string `json:"name"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Data []Channel `json:"data"`

	// HasMore True if there are more channels to fetch
	HasMore bool `json:"has_more"`
}

// CreateChannel defines model for CreateChannel.
type CreateChannel struct {
	// Name Name of the channel
	Name string `json:"name"`
}

// CreateOperation defines model for CreateOperation.
type CreateOperation struct {
	// Address Wallet address performing the operation
	Address string `json:"address"`

	// ChainFamily The blockchain family
	ChainFamily *string `json:"chain_family,omitempty"`

	// ChainId The ID that identifies the chain where the operation will be executed
	ChainId string `json:"chain_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Transactions List of transactions to execute
	Transactions []TransactionRequest `json:"transactions"`

	// WalletOperationId Unique wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// CreateWallet defines model for CreateWallet.
type CreateWallet struct {
	// Address EVM wallet address (42-character hex string starting with 0x)
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the wallet exists
	ChainId string `json:"chain_id"`

	// Name Name of the wallet
	Name *string `json:"name,omitempty"`
}

// CreateWatcher defines model for CreateWatcher.
type CreateWatcher struct {
	union json.RawMessage
}

// CreateWatcherWithABI defines model for CreateWatcherWithABI.
type CreateWatcherWithABI struct {
	// Abi ABI definitions for the events to watch
	Abi []EventABI `json:"abi"`

	// Address Smart contract address to watch for events
	Address string `json:"address"`

	// ChainFamily The blockchain family
	ChainFamily *string `json:"chain_family,omitempty"`

	// ChainId The ID that identifies the chain where the watcher will run
	ChainId string `json:"chain_id"`

	// Events List of event names to watch for
	Events []string `json:"events"`

	// Name Name for the watcher to help identify it
	Name *string `json:"name,omitempty"`
}

// CreateWatcherWithDomain defines model for CreateWatcherWithDomain.
type CreateWatcherWithDomain struct {
	// Address Smart contract address to watch for events
	Address string `json:"address"`

	// ChainFamily The blockchain family
	ChainFamily *string `json:"chain_family,omitempty"`

	// ChainId The ID that identifies the chain where the watcher will run
	ChainId string `json:"chain_id"`

	// Domain Service domain namespace (e.g., "dvp", "dta")
	Domain string `json:"domain"`

	// Events List of event names to watch for within the domain
	Events []string `json:"events"`

	// Name Name for the watcher to help identify it
	Name *string `json:"name,omitempty"`
}

// Event defines model for Event.
type Event struct {
	Headers EventHeaders  `json:"headers"`
	Payload Event_Payload `json:"payload"`
}

// Event_Payload defines model for Event.Payload.
type Event_Payload struct {
	union json.RawMessage
}

// EventABI defines model for EventABI.
type EventABI struct {
	// Anonymous Whether the event is anonymous
	Anonymous bool `json:"anonymous"`

	// Inputs Event input parameters
	Inputs []EventABIInput `json:"inputs"`

	// Name Name of the event
	Name string `json:"name"`

	// Type Type must be 'event'
	Type EventABIType `json:"type"`
}

// EventABIType Type must be 'event'
type EventABIType string

// EventABIInput defines model for EventABIInput.
type EventABIInput struct {
	// Indexed Whether the parameter is indexed
	Indexed bool `json:"indexed"`

	// InternalType Internal Solidity type
	InternalType string `json:"internalType"`

	// Name Parameter name
	Name string `json:"name"`

	// Type Parameter type
	Type string `json:"type"`
}

// EventHeaders defines model for EventHeaders.
type EventHeaders struct {
	// Offset Unique offset for message ordering
	Offset string                     `json:"offset"`
	Proofs []EventHeaders_Proofs_Item `json:"proofs"`
}

// EventHeadersProofs1 Generic proof object for future extensibility
type EventHeadersProofs1 map[string]interface{}

// EventHeaders_Proofs_Item defines model for EventHeaders.proofs.Item.
type EventHeaders_Proofs_Item struct {
	union json.RawMessage
}

// EventTransaction defines model for EventTransaction.
type EventTransaction struct {
	// Hash Transaction hash
	Hash string `json:"hash"`

	// Timestamp Transaction timestamp
	Timestamp int64 `json:"timestamp"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// OCRProof defines model for OCRProof.
type OCRProof struct {
	// Alg Algorithm used for the proof
	Alg string `json:"alg"`

	// OcrContext OCR context data
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report data
	OcrReport string `json:"ocr_report"`

	// Signatures Array of signatures
	Signatures []string `json:"signatures"`
}

// Operation defines model for Operation.
type Operation struct {
	// Address Wallet address performing the operation
	Address string `json:"address"`

	// ChainFamily The blockchain family
	ChainFamily string `json:"chain_family"`

	// ChainId The ID that identifies the chain where the operation is executed
	ChainId string `json:"chain_id"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt int64 `json:"created_at"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Status Current status of the operation
	Status string `json:"status"`

	// Transactions List of transactions to execute
	Transactions []TransactionRequest `json:"transactions"`

	// WalletOperationId Unique wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// OperationList defines model for OperationList.
type OperationList struct {
	Data []Operation `json:"data"`

	// HasMore True if there are more operations to fetch
	HasMore bool `json:"has_more"`
}

// OperationResponse defines model for OperationResponse.
type OperationResponse struct {
	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`
}

// OperationStatusPayload defines model for OperationStatusPayload.
type OperationStatusPayload struct {
	// Address Wallet address
	Address string `json:"address"`

	// ChainFamily Blockchain family (e.g., evm)
	ChainFamily string `json:"chain_family"`

	// ChainId Chain identifier
	ChainId string `json:"chain_id"`

	// Status Current status of the operation
	Status OperationStatusPayloadStatus `json:"status"`

	// StatusReason Reason for the status
	StatusReason string                     `json:"status_reason"`
	Transaction  *EventTransaction          `json:"transaction,omitempty"`
	Type         OperationStatusPayloadType `json:"type"`

	// WalletOperationId Wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// OperationStatusPayloadStatus Current status of the operation
type OperationStatusPayloadStatus string

// OperationStatusPayloadType defines model for OperationStatusPayload.Type.
type OperationStatusPayloadType string

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// UpdateWallet defines model for UpdateWallet.
type UpdateWallet struct {
	// Name New name for the wallet
	Name string `json:"name"`
}

// Wallet defines model for Wallet.
type Wallet struct {
	// Address EVM wallet address
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the wallet exists
	ChainId string `json:"chain_id"`

	// Name Name of the wallet
	Name *string `json:"name,omitempty"`

	// WalletId Unique identifier for the wallet
	WalletId openapi_types.UUID `json:"wallet_id"`
}

// WalletList defines model for WalletList.
type WalletList struct {
	Data []Wallet `json:"data"`

	// HasMore True if there are more wallets to fetch
	HasMore bool `json:"has_more"`
}

// Watcher defines model for Watcher.
type Watcher struct {
	// Abi ABI definitions for the events (if not using domain-based events)
	Abi *[]EventABI `json:"abi,omitempty"`

	// Address Smart contract address being watched
	Address string `json:"address"`

	// ChainFamily The blockchain family
	ChainFamily string `json:"chain_family"`

	// ChainId The ID that identifies the chain where the watcher runs
	ChainId string `json:"chain_id"`

	// ChannelId ID of the channel this watcher belongs to
	ChannelId openapi_types.UUID `json:"channel_id"`

	// CreatedAt Timestamp of when the watcher was created
	CreatedAt int64 `json:"created_at"`

	// Domain Service domain namespace (if using domain-based events)
	Domain *string `json:"domain,omitempty"`

	// Events List of event names being watched
	Events []string `json:"events"`

	// Name Name of the watcher for identification
	Name *string `json:"name,omitempty"`

	// Status Current status of the watcher
	Status string `json:"status"`

	// WatcherId Unique identifier for the watcher
	WatcherId openapi_types.UUID `json:"watcher_id"`
}

// WatcherEvent defines model for WatcherEvent.
type WatcherEvent struct {
	// Data Event data - can be any structure
	Data map[string]interface{} `json:"data"`

	// Domain Domain associated with the event (optional)
	Domain *string `json:"domain,omitempty"`

	// EventName Name of the event
	EventName string `json:"event_name"`

	// LogIndex Log index in the transaction
	LogIndex int `json:"log_index"`

	// Metadata Event metadata - can be any structure
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Timestamp Event timestamp
	Timestamp time.Time `json:"timestamp"`

	// TopicHash Event topic hash
	TopicHash string `json:"topic_hash"`
}

// WatcherEventPayload defines model for WatcherEventPayload.
type WatcherEventPayload struct {
	// Address Contract address that emitted the event
	Address string `json:"address"`

	// ChainFamily Blockchain family (e.g., evm)
	ChainFamily string `json:"chain_family"`

	// ChainId Chain identifier
	ChainId     string                  `json:"chain_id"`
	Event       WatcherEvent            `json:"event"`
	Transaction EventTransaction        `json:"transaction"`
	Type        WatcherEventPayloadType `json:"type"`

	// WatcherId Unique watcher identifier
	WatcherId string `json:"watcher_id"`
}

// WatcherEventPayloadType defines model for WatcherEventPayload.Type.
type WatcherEventPayloadType string

// WatcherList defines model for WatcherList.
type WatcherList struct {
	Data []Watcher `json:"data"`

	// HasMore True if there are more watchers to fetch
	HasMore bool `json:"has_more"`
}

// WatcherStatusPayload defines model for WatcherStatusPayload.
type WatcherStatusPayload struct {
	// ChainFamily Blockchain family (e.g., evm)
	ChainFamily string `json:"chain_family"`

	// ChainId Chain identifier
	ChainId string `json:"chain_id"`

	// Status Current status of the watcher
	Status WatcherStatusPayloadStatus `json:"status"`

	// StatusCode Status code
	StatusCode string `json:"status_code"`

	// StatusReason Reason for the status
	StatusReason string                   `json:"status_reason"`
	Type         WatcherStatusPayloadType `json:"type"`

	// WatcherId Unique watcher identifier
	WatcherId string `json:"watcher_id"`
}

// WatcherStatusPayloadStatus Current status of the watcher
type WatcherStatusPayloadStatus string

// WatcherStatusPayloadType defines model for WatcherStatusPayload.Type.
type WatcherStatusPayloadType string

// GetChannelsParams defines parameters for GetChannels.
type GetChannelsParams struct {
	// Name Filter channels by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Limit Maximum number of channels to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of channels to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetChannelsChannelIdEventsParams defines parameters for GetChannelsChannelIdEvents.
type GetChannelsChannelIdEventsParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for message-oriented pagination
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`

	// Type Filter events by type
	Type *GetChannelsChannelIdEventsParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Status Filter by operation or watcher status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// EventName Filter by event name (for watcher.event type)
	EventName *string `form:"event_name,omitempty" json:"event_name,omitempty"`

	// Domain Filter by watcher domain (for watcher events)
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`
}

// GetChannelsChannelIdEventsParamsType defines parameters for GetChannelsChannelIdEvents.
type GetChannelsChannelIdEventsParamsType string

// GetChannelsChannelIdOperationsParams defines parameters for GetChannelsChannelIdOperations.
type GetChannelsChannelIdOperationsParams struct {
	// Limit Maximum number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of operations to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Status Filter operations by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// ChainFamily Filter operations by blockchain family
	ChainFamily *string `form:"chain_family,omitempty" json:"chain_family,omitempty"`

	// ChainId Filter operations by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Address Filter operations by wallet address
	Address *string `form:"address,omitempty" json:"address,omitempty"`
}

// GetChannelsChannelIdWatchersParams defines parameters for GetChannelsChannelIdWatchers.
type GetChannelsChannelIdWatchersParams struct {
	// Limit Maximum number of watchers to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of watchers to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Status Filter watchers by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// ChainFamily Filter watchers by blockchain family
	ChainFamily *string `form:"chain_family,omitempty" json:"chain_family,omitempty"`

	// ChainId Filter watchers by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Address Filter watchers by contract address
	Address *string `form:"address,omitempty" json:"address,omitempty"`

	// Domain Filter watchers by domain
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`

	// EventName Filter watchers by event name
	EventName *string `form:"event_name,omitempty" json:"event_name,omitempty"`
}

// GetWalletsParams defines parameters for GetWallets.
type GetWalletsParams struct {
	// Name Filter wallets by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// ChainId Filter wallets by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Limit Maximum number of wallets to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of wallets to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostChannelsJSONRequestBody defines body for PostChannels for application/json ContentType.
type PostChannelsJSONRequestBody = CreateChannel

// PostChannelsChannelIdOperationsJSONRequestBody defines body for PostChannelsChannelIdOperations for application/json ContentType.
type PostChannelsChannelIdOperationsJSONRequestBody = CreateOperation

// PostChannelsChannelIdWatchersJSONRequestBody defines body for PostChannelsChannelIdWatchers for application/json ContentType.
type PostChannelsChannelIdWatchersJSONRequestBody = CreateWatcher

// PostWalletsJSONRequestBody defines body for PostWallets for application/json ContentType.
type PostWalletsJSONRequestBody = CreateWallet

// PatchWalletsWalletIdJSONRequestBody defines body for PatchWalletsWalletId for application/json ContentType.
type PatchWalletsWalletIdJSONRequestBody = UpdateWallet

// AsCreateWatcherWithDomain returns the union data inside the CreateWatcher as a CreateWatcherWithDomain
func (t CreateWatcher) AsCreateWatcherWithDomain() (CreateWatcherWithDomain, error) {
	var body CreateWatcherWithDomain
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateWatcherWithDomain overwrites any union data inside the CreateWatcher as the provided CreateWatcherWithDomain
func (t *CreateWatcher) FromCreateWatcherWithDomain(v CreateWatcherWithDomain) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateWatcherWithDomain performs a merge with any union data inside the CreateWatcher, using the provided CreateWatcherWithDomain
func (t *CreateWatcher) MergeCreateWatcherWithDomain(v CreateWatcherWithDomain) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateWatcherWithABI returns the union data inside the CreateWatcher as a CreateWatcherWithABI
func (t CreateWatcher) AsCreateWatcherWithABI() (CreateWatcherWithABI, error) {
	var body CreateWatcherWithABI
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateWatcherWithABI overwrites any union data inside the CreateWatcher as the provided CreateWatcherWithABI
func (t *CreateWatcher) FromCreateWatcherWithABI(v CreateWatcherWithABI) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateWatcherWithABI performs a merge with any union data inside the CreateWatcher, using the provided CreateWatcherWithABI
func (t *CreateWatcher) MergeCreateWatcherWithABI(v CreateWatcherWithABI) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateWatcher) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateWatcher) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOperationStatusPayload returns the union data inside the Event_Payload as a OperationStatusPayload
func (t Event_Payload) AsOperationStatusPayload() (OperationStatusPayload, error) {
	var body OperationStatusPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOperationStatusPayload overwrites any union data inside the Event_Payload as the provided OperationStatusPayload
func (t *Event_Payload) FromOperationStatusPayload(v OperationStatusPayload) error {
	v.Type = "OperationStatusPayload"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOperationStatusPayload performs a merge with any union data inside the Event_Payload, using the provided OperationStatusPayload
func (t *Event_Payload) MergeOperationStatusPayload(v OperationStatusPayload) error {
	v.Type = "OperationStatusPayload"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWatcherStatusPayload returns the union data inside the Event_Payload as a WatcherStatusPayload
func (t Event_Payload) AsWatcherStatusPayload() (WatcherStatusPayload, error) {
	var body WatcherStatusPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWatcherStatusPayload overwrites any union data inside the Event_Payload as the provided WatcherStatusPayload
func (t *Event_Payload) FromWatcherStatusPayload(v WatcherStatusPayload) error {
	v.Type = "WatcherStatusPayload"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWatcherStatusPayload performs a merge with any union data inside the Event_Payload, using the provided WatcherStatusPayload
func (t *Event_Payload) MergeWatcherStatusPayload(v WatcherStatusPayload) error {
	v.Type = "WatcherStatusPayload"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWatcherEventPayload returns the union data inside the Event_Payload as a WatcherEventPayload
func (t Event_Payload) AsWatcherEventPayload() (WatcherEventPayload, error) {
	var body WatcherEventPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWatcherEventPayload overwrites any union data inside the Event_Payload as the provided WatcherEventPayload
func (t *Event_Payload) FromWatcherEventPayload(v WatcherEventPayload) error {
	v.Type = "WatcherEventPayload"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWatcherEventPayload performs a merge with any union data inside the Event_Payload, using the provided WatcherEventPayload
func (t *Event_Payload) MergeWatcherEventPayload(v WatcherEventPayload) error {
	v.Type = "WatcherEventPayload"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event_Payload) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event_Payload) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "OperationStatusPayload":
		return t.AsOperationStatusPayload()
	case "WatcherEventPayload":
		return t.AsWatcherEventPayload()
	case "WatcherStatusPayload":
		return t.AsWatcherStatusPayload()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOCRProof returns the union data inside the EventHeaders_Proofs_Item as a OCRProof
func (t EventHeaders_Proofs_Item) AsOCRProof() (OCRProof, error) {
	var body OCRProof
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOCRProof overwrites any union data inside the EventHeaders_Proofs_Item as the provided OCRProof
func (t *EventHeaders_Proofs_Item) FromOCRProof(v OCRProof) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOCRProof performs a merge with any union data inside the EventHeaders_Proofs_Item, using the provided OCRProof
func (t *EventHeaders_Proofs_Item) MergeOCRProof(v OCRProof) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventHeadersProofs1 returns the union data inside the EventHeaders_Proofs_Item as a EventHeadersProofs1
func (t EventHeaders_Proofs_Item) AsEventHeadersProofs1() (EventHeadersProofs1, error) {
	var body EventHeadersProofs1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventHeadersProofs1 overwrites any union data inside the EventHeaders_Proofs_Item as the provided EventHeadersProofs1
func (t *EventHeaders_Proofs_Item) FromEventHeadersProofs1(v EventHeadersProofs1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventHeadersProofs1 performs a merge with any union data inside the EventHeaders_Proofs_Item, using the provided EventHeadersProofs1
func (t *EventHeaders_Proofs_Item) MergeEventHeadersProofs1(v EventHeadersProofs1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventHeaders_Proofs_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventHeaders_Proofs_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves channels for the organization.
	// (GET /channels)
	GetChannels(c *gin.Context, params GetChannelsParams)
	// Creates a new channel.
	// (POST /channels)
	PostChannels(c *gin.Context)
	// Deletes a channel.
	// (DELETE /channels/{channel_id})
	DeleteChannelsChannelId(c *gin.Context, channelId openapi_types.UUID)
	// Retrieves a specific channel by ID.
	// (GET /channels/{channel_id})
	GetChannelsChannelId(c *gin.Context, channelId openapi_types.UUID)
	// Retrieves events from a channel.
	// (GET /channels/{channel_id}/events)
	GetChannelsChannelIdEvents(c *gin.Context, channelId openapi_types.UUID, params GetChannelsChannelIdEventsParams)
	// Retrieves operations for a channel.
	// (GET /channels/{channel_id}/operations)
	GetChannelsChannelIdOperations(c *gin.Context, channelId openapi_types.UUID, params GetChannelsChannelIdOperationsParams)
	// Sends a CreateOperation request to a channel.
	// (POST /channels/{channel_id}/operations)
	PostChannelsChannelIdOperations(c *gin.Context, channelId openapi_types.UUID)
	// Gets Operation record for a specific operation.
	// (GET /channels/{channel_id}/operations/{operation_id})
	GetChannelsChannelIdOperationsOperationId(c *gin.Context, channelId openapi_types.UUID, operationId openapi_types.UUID)
	// Retrieves watchers for a channel.
	// (GET /channels/{channel_id}/watchers)
	GetChannelsChannelIdWatchers(c *gin.Context, channelId openapi_types.UUID, params GetChannelsChannelIdWatchersParams)
	// Creates a watcher in a channel.
	// (POST /channels/{channel_id}/watchers)
	PostChannelsChannelIdWatchers(c *gin.Context, channelId openapi_types.UUID)
	// Deletes a watcher.
	// (DELETE /channels/{channel_id}/watchers/{watcher_id})
	DeleteChannelsChannelIdWatchersWatcherId(c *gin.Context, channelId openapi_types.UUID, watcherId openapi_types.UUID)
	// Retrieves a specific watcher by ID.
	// (GET /channels/{channel_id}/watchers/{watcher_id})
	GetChannelsChannelIdWatchersWatcherId(c *gin.Context, channelId openapi_types.UUID, watcherId openapi_types.UUID)
	// Health check endpoint
	// (GET /health-check)
	GetHealthCheck(c *gin.Context)
	// Retrieves wallets for the organization.
	// (GET /wallets)
	GetWallets(c *gin.Context, params GetWalletsParams)
	// Creates a new wallet.
	// (POST /wallets)
	PostWallets(c *gin.Context)
	// Retrieves a specific wallet by ID.
	// (GET /wallets/{wallet_id})
	GetWalletsWalletId(c *gin.Context, walletId openapi_types.UUID)
	// Updates a wallet name.
	// (PATCH /wallets/{wallet_id})
	PatchWalletsWalletId(c *gin.Context, walletId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetChannels operation middleware
func (siw *ServerInterfaceWrapper) GetChannels(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannels(c, params)
}

// PostChannels operation middleware
func (siw *ServerInterfaceWrapper) PostChannels(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostChannels(c)
}

// DeleteChannelsChannelId operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelsChannelId(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChannelsChannelId(c, channelId)
}

// GetChannelsChannelId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelId(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelId(c, channelId)
}

// GetChannelsChannelIdEvents operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdEvents(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", c.Request.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "event_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "event_name", c.Request.URL.Query(), &params.EventName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter event_name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "domain" -------------

	err = runtime.BindQueryParameter("form", true, false, "domain", c.Request.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter domain: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelIdEvents(c, channelId, params)
}

// GetChannelsChannelIdOperations operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdOperations(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdOperationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_family" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_family", c.Request.URL.Query(), &params.ChainFamily)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_family: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "address" -------------

	err = runtime.BindQueryParameter("form", true, false, "address", c.Request.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter address: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelIdOperations(c, channelId, params)
}

// PostChannelsChannelIdOperations operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsChannelIdOperations(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostChannelsChannelIdOperations(c, channelId)
}

// GetChannelsChannelIdOperationsOperationId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdOperationsOperationId(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "operation_id" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", c.Param("operation_id"), &operationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelIdOperationsOperationId(c, channelId, operationId)
}

// GetChannelsChannelIdWatchers operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdWatchers(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdWatchersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_family" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_family", c.Request.URL.Query(), &params.ChainFamily)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_family: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "address" -------------

	err = runtime.BindQueryParameter("form", true, false, "address", c.Request.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter address: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "domain" -------------

	err = runtime.BindQueryParameter("form", true, false, "domain", c.Request.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter domain: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "event_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "event_name", c.Request.URL.Query(), &params.EventName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter event_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelIdWatchers(c, channelId, params)
}

// PostChannelsChannelIdWatchers operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsChannelIdWatchers(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostChannelsChannelIdWatchers(c, channelId)
}

// DeleteChannelsChannelIdWatchersWatcherId operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelsChannelIdWatchersWatcherId(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "watcher_id" -------------
	var watcherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "watcher_id", c.Param("watcher_id"), &watcherId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter watcher_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChannelsChannelIdWatchersWatcherId(c, channelId, watcherId)
}

// GetChannelsChannelIdWatchersWatcherId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdWatchersWatcherId(c *gin.Context) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", c.Param("channel_id"), &channelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "watcher_id" -------------
	var watcherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "watcher_id", c.Param("watcher_id"), &watcherId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter watcher_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChannelsChannelIdWatchersWatcherId(c, channelId, watcherId)
}

// GetHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthCheck(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthCheck(c)
}

// GetWallets operation middleware
func (siw *ServerInterfaceWrapper) GetWallets(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWalletsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWallets(c, params)
}

// PostWallets operation middleware
func (siw *ServerInterfaceWrapper) PostWallets(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostWallets(c)
}

// GetWalletsWalletId operation middleware
func (siw *ServerInterfaceWrapper) GetWalletsWalletId(c *gin.Context) {

	var err error

	// ------------- Path parameter "wallet_id" -------------
	var walletId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_id", c.Param("wallet_id"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter wallet_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWalletsWalletId(c, walletId)
}

// PatchWalletsWalletId operation middleware
func (siw *ServerInterfaceWrapper) PatchWalletsWalletId(c *gin.Context) {

	var err error

	// ------------- Path parameter "wallet_id" -------------
	var walletId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_id", c.Param("wallet_id"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter wallet_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchWalletsWalletId(c, walletId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/channels", wrapper.GetChannels)
	router.POST(options.BaseURL+"/channels", wrapper.PostChannels)
	router.DELETE(options.BaseURL+"/channels/:channel_id", wrapper.DeleteChannelsChannelId)
	router.GET(options.BaseURL+"/channels/:channel_id", wrapper.GetChannelsChannelId)
	router.GET(options.BaseURL+"/channels/:channel_id/events", wrapper.GetChannelsChannelIdEvents)
	router.GET(options.BaseURL+"/channels/:channel_id/operations", wrapper.GetChannelsChannelIdOperations)
	router.POST(options.BaseURL+"/channels/:channel_id/operations", wrapper.PostChannelsChannelIdOperations)
	router.GET(options.BaseURL+"/channels/:channel_id/operations/:operation_id", wrapper.GetChannelsChannelIdOperationsOperationId)
	router.GET(options.BaseURL+"/channels/:channel_id/watchers", wrapper.GetChannelsChannelIdWatchers)
	router.POST(options.BaseURL+"/channels/:channel_id/watchers", wrapper.PostChannelsChannelIdWatchers)
	router.DELETE(options.BaseURL+"/channels/:channel_id/watchers/:watcher_id", wrapper.DeleteChannelsChannelIdWatchersWatcherId)
	router.GET(options.BaseURL+"/channels/:channel_id/watchers/:watcher_id", wrapper.GetChannelsChannelIdWatchersWatcherId)
	router.GET(options.BaseURL+"/health-check", wrapper.GetHealthCheck)
	router.GET(options.BaseURL+"/wallets", wrapper.GetWallets)
	router.POST(options.BaseURL+"/wallets", wrapper.PostWallets)
	router.GET(options.BaseURL+"/wallets/:wallet_id", wrapper.GetWalletsWalletId)
	router.PATCH(options.BaseURL+"/wallets/:wallet_id", wrapper.PatchWalletsWalletId)
}
