// Package ginserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ginserver

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ApplicationErrorType.
const (
	AlreadyExists ApplicationErrorType = "Already exists"
	BadRequest    ApplicationErrorType = "Bad request"
	InternalError ApplicationErrorType = "Internal error"
	NotFound      ApplicationErrorType = "Not found"
)

// Account defines model for Account.
type Account struct {
	// AccountId Unique identifier for the account
	AccountId openapi_types.UUID `json:"account_id"`

	// Address EVM account address
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the account exists
	ChainId string `json:"chain_id"`

	// Name Name of the account
	Name *string `json:"name,omitempty"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Data []Account `json:"data"`

	// HasMore True if there are more accounts to fetch
	HasMore bool `json:"has_more"`
}

// ApplicationError defines model for ApplicationError.
type ApplicationError struct {
	// Message Error message describing the issue
	Message string `json:"message"`

	// Type Error type
	Type ApplicationErrorType `json:"type"`
}

// ApplicationErrorType Error type
type ApplicationErrorType string

// CreateAccount defines model for CreateAccount.
type CreateAccount struct {
	// Address EVM account address (42-character hex string starting with 0x)
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the account exists
	ChainId string `json:"chain_id"`

	// Name Name of the account
	Name *string `json:"name,omitempty"`
}

// CreateEvent defines model for CreateEvent.
type CreateEvent struct {
	// Address Smart contract address from which the event was emitted
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the event happened
	ChainId string `json:"chain_id"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// CreateListener defines model for CreateListener.
type CreateListener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// ChainFamily (Optional) the network to use.
	ChainFamily *string `json:"chain_family,omitempty"`

	// ChainId The id that identifies the chain where the listener will run
	ChainId string `json:"chain_id"`

	// Name Name of the event to listen for
	Name    string             `json:"name"`
	Options *map[string]string `json:"options,omitempty"`

	// Service Service namespace for the listener
	Service string `json:"service"`
}

// CreateOperation defines model for CreateOperation.
type CreateOperation struct {
	// AccountAddress Onchain account address performing the operation
	AccountAddress string `json:"account_address"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// Signature EIP-712 signature of the operation
	Signature    string               `json:"signature"`
	Transactions []TransactionRequest `json:"transactions"`
}

// Event defines model for Event.
type Event struct {
	// Address The address of the smart contract from which the event was emitted
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the event happened
	ChainId string `json:"chain_id"`

	// CreatedAt Timestamp of when the event was created
	CreatedAt int64 `json:"created_at"`

	// EventHash Deterministic event hash - keccak256(service.name.base64payload)
	EventHash string `json:"event_hash"`

	// EventId Unique identifier for the event
	EventId openapi_types.UUID `json:"event_id"`

	// ListenerId Listener UUID that emitted the event
	ListenerId openapi_types.UUID `json:"listener_id"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// EventList defines model for EventList.
type EventList struct {
	Data []Event `json:"data"`

	// HasMore True if there are more events to fetch
	HasMore bool `json:"has_more"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// Listener defines model for Listener.
type Listener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the listener will run
	ChainId string `json:"chain_id"`

	// CreatedAt Timestamp of when the listener was created
	CreatedAt int64 `json:"created_at"`

	// ListenerId Unique identifier for the listener
	ListenerId openapi_types.UUID `json:"listener_id"`

	// Name Name of the event to listen for
	Name    string            `json:"name"`
	Options map[string]string `json:"options"`

	// Service Service namespace for the listener
	Service string `json:"service"`

	// Status Current status of the listener
	Status string `json:"status"`
}

// ListenerList defines model for ListenerList.
type ListenerList struct {
	Data []Listener `json:"data"`

	// HasMore True if there are more listeners to fetch
	HasMore bool `json:"has_more"`
}

// Operation defines model for Operation.
type Operation struct {
	// AccountAddress Onchain account address performing the operation
	AccountAddress string `json:"account_address"`

	// AccountId Identifier of the account performing the operation
	AccountId openapi_types.UUID `json:"account_id"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// ConfirmedAt Timestamp of when the operation was confirmed
	ConfirmedAt *int64 `json:"confirmed_at,omitempty"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt int64 `json:"created_at"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Status Current status of the operation
	Status string `json:"status"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash *string       `json:"transaction_hash,omitempty"`
	Transactions    []Transaction `json:"transactions"`
}

// OperationList defines model for OperationList.
type OperationList struct {
	Data []Operation `json:"data"`

	// HasMore True if there are more operations to fetch
	HasMore bool `json:"has_more"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// UpdateAccount defines model for UpdateAccount.
type UpdateAccount struct {
	// Name New name for the account
	Name string `json:"name"`
}

// UpdateOperationStatus defines model for UpdateOperationStatus.
type UpdateOperationStatus struct {
	// AccountAddress Onchain account address performing the operation
	AccountAddress string `json:"account_address"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash string `json:"transaction_hash"`

	// TransactionTimestamp Timestamp of onchain transaction which included the operation
	TransactionTimestamp int `json:"transaction_timestamp"`
}

// GetAccountsParams defines parameters for GetAccounts.
type GetAccountsParams struct {
	// Name Filter accounts by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// ChainId Filter accounts by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Limit Maximum number of accounts to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of accounts to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// ListenerId Return only events emitted by this listener UUID
	ListenerId *openapi_types.UUID `form:"listener_id,omitempty" json:"listener_id,omitempty"`

	// ChainId Filter events by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetListenersParams defines parameters for GetListeners.
type GetListenersParams struct {
	// ChainId Filter listeners by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Status Filter listeners by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Name Filter listeners by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Service Filter listeners by service
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetOperationsParams defines parameters for GetOperations.
type GetOperationsParams struct {
	// CreatedLt Filter operations created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter operations created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter operations created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter operations created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// AccountName Filter operations by account name (partial match)
	AccountName *string `form:"account_name,omitempty" json:"account_name,omitempty"`

	// Status Filter operations by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// ChainId Filter operations by chain ID
	ChainId *string `form:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Limit The number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return operations starting after this operation UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return operations occurring before this operation UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// PostAccountsJSONRequestBody defines body for PostAccounts for application/json ContentType.
type PostAccountsJSONRequestBody = CreateAccount

// PutAccountsAccountIdJSONRequestBody defines body for PutAccountsAccountId for application/json ContentType.
type PutAccountsAccountIdJSONRequestBody = UpdateAccount

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody = CreateEvent

// PostListenersJSONRequestBody defines body for PostListeners for application/json ContentType.
type PostListenersJSONRequestBody = CreateListener

// PostOperationStatusJSONRequestBody defines body for PostOperationStatus for application/json ContentType.
type PostOperationStatusJSONRequestBody = UpdateOperationStatus

// PostOperationsJSONRequestBody defines body for PostOperations for application/json ContentType.
type PostOperationsJSONRequestBody = CreateOperation

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves accounts for the organization.
	// (GET /accounts)
	GetAccounts(c *gin.Context, params GetAccountsParams)
	// Creates a new account.
	// (POST /accounts)
	PostAccounts(c *gin.Context)
	// Retrieves a specific account by ID.
	// (GET /accounts/{account_id})
	GetAccountsAccountId(c *gin.Context, accountId openapi_types.UUID)
	// Updates an account name.
	// (PUT /accounts/{account_id})
	PutAccountsAccountId(c *gin.Context, accountId openapi_types.UUID)
	// Retrieves events.
	// (GET /events)
	GetEvents(c *gin.Context, params GetEventsParams)
	// Creates a new event.
	// (POST /events)
	PostEvents(c *gin.Context)
	// Retrieves a single event.
	// (GET /events/{event_id})
	GetEventsEventId(c *gin.Context, eventId openapi_types.UUID)
	// Health check endpoint
	// (GET /health-check)
	GetHealthCheck(c *gin.Context)
	// Retrieves event listeners.
	// (GET /listeners)
	GetListeners(c *gin.Context, params GetListenersParams)
	// Creates a new listener.
	// (POST /listeners)
	PostListeners(c *gin.Context)
	// Deletes a listener.
	// (DELETE /listeners/{listener_id})
	DeleteListenersListenerId(c *gin.Context, listenerId openapi_types.UUID)
	// Retrieves a single listener.
	// (GET /listeners/{listener_id})
	GetListenersListenerId(c *gin.Context, listenerId openapi_types.UUID)
	// Updates the status of an operation.
	// (POST /operation_status)
	PostOperationStatus(c *gin.Context)
	// Retrieves operations.
	// (GET /operations)
	GetOperations(c *gin.Context, params GetOperationsParams)
	// Sends an onchain transaction.
	// (POST /operations)
	PostOperations(c *gin.Context)
	// Retrieves the status of an operation.
	// (GET /operations/{operation_id})
	GetOperationsOperationId(c *gin.Context, operationId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccounts(c, params)
}

// PostAccounts operation middleware
func (siw *ServerInterfaceWrapper) PostAccounts(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAccounts(c)
}

// GetAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountsAccountId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountsAccountId(c, accountId)
}

// PutAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) PutAccountsAccountId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutAccountsAccountId(c, accountId)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "listener_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "listener_id", c.Request.URL.Query(), &params.ListenerId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter listener_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", c.Request.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", c.Request.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", c.Request.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", c.Request.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", c.Request.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter starting_after: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", c.Request.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ending_before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEvents(c, params)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostEvents(c)
}

// GetEventsEventId operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventId(c *gin.Context) {

	var err error

	// ------------- Path parameter "event_id" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "event_id", c.Param("event_id"), &eventId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter event_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEventsEventId(c, eventId)
}

// GetHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthCheck(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthCheck(c)
}

// GetListeners operation middleware
func (siw *ServerInterfaceWrapper) GetListeners(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListenersParams

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "service" -------------

	err = runtime.BindQueryParameter("form", true, false, "service", c.Request.URL.Query(), &params.Service)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", c.Request.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", c.Request.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", c.Request.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", c.Request.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", c.Request.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter starting_after: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", c.Request.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ending_before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListeners(c, params)
}

// PostListeners operation middleware
func (siw *ServerInterfaceWrapper) PostListeners(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostListeners(c)
}

// DeleteListenersListenerId operation middleware
func (siw *ServerInterfaceWrapper) DeleteListenersListenerId(c *gin.Context) {

	var err error

	// ------------- Path parameter "listener_id" -------------
	var listenerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "listener_id", c.Param("listener_id"), &listenerId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter listener_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteListenersListenerId(c, listenerId)
}

// GetListenersListenerId operation middleware
func (siw *ServerInterfaceWrapper) GetListenersListenerId(c *gin.Context) {

	var err error

	// ------------- Path parameter "listener_id" -------------
	var listenerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "listener_id", c.Param("listener_id"), &listenerId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter listener_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListenersListenerId(c, listenerId)
}

// PostOperationStatus operation middleware
func (siw *ServerInterfaceWrapper) PostOperationStatus(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostOperationStatus(c)
}

// GetOperations operation middleware
func (siw *ServerInterfaceWrapper) GetOperations(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOperationsParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", c.Request.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", c.Request.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.lte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", c.Request.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gt: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", c.Request.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created.gte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "account_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_name", c.Request.URL.Query(), &params.AccountName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_id", c.Request.URL.Query(), &params.ChainId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chain_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", c.Request.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter starting_after: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", c.Request.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ending_before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOperations(c, params)
}

// PostOperations operation middleware
func (siw *ServerInterfaceWrapper) PostOperations(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostOperations(c)
}

// GetOperationsOperationId operation middleware
func (siw *ServerInterfaceWrapper) GetOperationsOperationId(c *gin.Context) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", c.Param("operation_id"), &operationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOperationsOperationId(c, operationId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/accounts", wrapper.GetAccounts)
	router.POST(options.BaseURL+"/accounts", wrapper.PostAccounts)
	router.GET(options.BaseURL+"/accounts/:account_id", wrapper.GetAccountsAccountId)
	router.PUT(options.BaseURL+"/accounts/:account_id", wrapper.PutAccountsAccountId)
	router.GET(options.BaseURL+"/events", wrapper.GetEvents)
	router.POST(options.BaseURL+"/events", wrapper.PostEvents)
	router.GET(options.BaseURL+"/events/:event_id", wrapper.GetEventsEventId)
	router.GET(options.BaseURL+"/health-check", wrapper.GetHealthCheck)
	router.GET(options.BaseURL+"/listeners", wrapper.GetListeners)
	router.POST(options.BaseURL+"/listeners", wrapper.PostListeners)
	router.DELETE(options.BaseURL+"/listeners/:listener_id", wrapper.DeleteListenersListenerId)
	router.GET(options.BaseURL+"/listeners/:listener_id", wrapper.GetListenersListenerId)
	router.POST(options.BaseURL+"/operation_status", wrapper.PostOperationStatus)
	router.GET(options.BaseURL+"/operations", wrapper.GetOperations)
	router.POST(options.BaseURL+"/operations", wrapper.PostOperations)
	router.GET(options.BaseURL+"/operations/:operation_id", wrapper.GetOperationsOperationId)
}
