//go:build go1.22

// Package stdserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package stdserver

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ApplicationErrorType.
const (
	AlreadyExists ApplicationErrorType = "Already exists"
	BadRequest    ApplicationErrorType = "Bad request"
	InternalError ApplicationErrorType = "Internal error"
	NotFound      ApplicationErrorType = "Not found"
)

// Defines values for CreateWalletWalletType.
const (
	CreateWalletWalletTypeEcdsa CreateWalletWalletType = "ecdsa"
	CreateWalletWalletTypeRsa   CreateWalletWalletType = "rsa"
)

// Defines values for EventABIType.
const (
	EventABITypeEvent EventABIType = "event"
)

// Defines values for EventHeadersType.
const (
	EventHeadersTypeOperationStatus EventHeadersType = "operation.status"
	EventHeadersTypeWalletStatus    EventHeadersType = "wallet.status"
	EventHeadersTypeWatcherEvent    EventHeadersType = "watcher.event"
	EventHeadersTypeWatcherStatus   EventHeadersType = "watcher.status"
)

// Defines values for OperationStatusPayloadStatus.
const (
	OperationStatusPayloadStatusBroadcasting OperationStatusPayloadStatus = "broadcasting"
	OperationStatusPayloadStatusConfirmed    OperationStatusPayloadStatus = "confirmed"
	OperationStatusPayloadStatusFailed       OperationStatusPayloadStatus = "failed"
	OperationStatusPayloadStatusPending      OperationStatusPayloadStatus = "pending"
	OperationStatusPayloadStatusSent         OperationStatusPayloadStatus = "sent"
)

// Defines values for OperationStatusPayloadType.
const (
	OperationStatusPayloadTypeOperationStatus OperationStatusPayloadType = "operation.status"
)

// Defines values for WalletWalletType.
const (
	WalletWalletTypeEcdsa WalletWalletType = "ecdsa"
	WalletWalletTypeRsa   WalletWalletType = "rsa"
)

// Defines values for WalletStatusPayloadStatus.
const (
	WalletStatusPayloadStatusDeployed  WalletStatusPayloadStatus = "deployed"
	WalletStatusPayloadStatusDeploying WalletStatusPayloadStatus = "deploying"
	WalletStatusPayloadStatusFailed    WalletStatusPayloadStatus = "failed"
	WalletStatusPayloadStatusPending   WalletStatusPayloadStatus = "pending"
)

// Defines values for WalletStatusPayloadType.
const (
	WalletStatusPayloadTypeWalletStatus WalletStatusPayloadType = "wallet.status"
)

// Defines values for WatcherEventPayloadType.
const (
	WatcherEvent WatcherEventPayloadType = "watcher.event"
)

// Defines values for WatcherStatusPayloadStatus.
const (
	WatcherStatusPayloadStatusDeleted   WatcherStatusPayloadStatus = "deleted"
	WatcherStatusPayloadStatusDeleting  WatcherStatusPayloadStatus = "deleting"
	WatcherStatusPayloadStatusDeploying WatcherStatusPayloadStatus = "deploying"
	WatcherStatusPayloadStatusFailed    WatcherStatusPayloadStatus = "failed"
	WatcherStatusPayloadStatusPending   WatcherStatusPayloadStatus = "pending"
	WatcherStatusPayloadStatusRemoved   WatcherStatusPayloadStatus = "removed"
)

// Defines values for WatcherStatusPayloadType.
const (
	WatcherStatus WatcherStatusPayloadType = "watcher.status"
)

// Defines values for GetChannelsChannelIdEventsSearchParamsType.
const (
	GetChannelsChannelIdEventsSearchParamsTypeOperationStatus GetChannelsChannelIdEventsSearchParamsType = "operation.status"
	GetChannelsChannelIdEventsSearchParamsTypeWalletStatus    GetChannelsChannelIdEventsSearchParamsType = "wallet.status"
	GetChannelsChannelIdEventsSearchParamsTypeWatcherEvent    GetChannelsChannelIdEventsSearchParamsType = "watcher.event"
	GetChannelsChannelIdEventsSearchParamsTypeWatcherStatus   GetChannelsChannelIdEventsSearchParamsType = "watcher.status"
)

// Defines values for GetWalletsParamsType.
const (
	Ecdsa GetWalletsParamsType = "ecdsa"
	Rsa   GetWalletsParamsType = "rsa"
)

// Defines values for GetWalletsParamsStatus.
const (
	GetWalletsParamsStatusDeployed  GetWalletsParamsStatus = "deployed"
	GetWalletsParamsStatusDeploying GetWalletsParamsStatus = "deploying"
	GetWalletsParamsStatusFailed    GetWalletsParamsStatus = "failed"
	GetWalletsParamsStatusPending   GetWalletsParamsStatus = "pending"
)

// ApplicationError defines model for ApplicationError.
type ApplicationError struct {
	// Message Error message describing the issue
	Message string `json:"message"`

	// Type Error type
	Type ApplicationErrorType `json:"type"`
}

// ApplicationErrorType Error type
type ApplicationErrorType string

// Channel defines model for Channel.
type Channel struct {
	// ChannelId Unique identifier for the channel
	ChannelId openapi_types.UUID `json:"channel_id"`

	// CreatedAt Timestamp of when the channel was created
	CreatedAt int64 `json:"created_at"`

	// Description Description of the channel
	Description *string `json:"description,omitempty"`

	// Name Name of the channel
	Name string `json:"name"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Data []Channel `json:"data"`

	// HasMore True if there are more channels to fetch
	HasMore bool `json:"has_more"`
}

// CreateChannel defines model for CreateChannel.
type CreateChannel struct {
	// Description Description of the channel
	Description *string `json:"description,omitempty"`

	// Name Name of the channel
	Name string `json:"name"`
}

// CreateOperation defines model for CreateOperation.
type CreateOperation struct {
	// Address Wallet address performing the operation
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the operation will be executed
	ChainSelector string `json:"chain_selector"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Transactions List of transactions to execute
	Transactions []TransactionRequest `json:"transactions"`

	// WalletOperationId Unique wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// CreateWallet defines model for CreateWallet.
type CreateWallet struct {
	// AllowedEcdsaSigners Allowed ECDSA public signing keys for the wallet
	AllowedEcdsaSigners *[]string `json:"allowed_ecdsa_signers,omitempty"`

	// AllowedRsaSigners Allowed RSA public signing keys for the wallet
	AllowedRsaSigners *[]struct {
		// E RSA public exponent of allowed signer
		E string `json:"e"`

		// N RSA modulus of allowed signer
		N string `json:"n"`
	} `json:"allowed_rsa_signers,omitempty"`

	// ChainSelector The id that identifies the chain where the wallet exists
	ChainSelector string `json:"chain_selector"`

	// Name Name of the wallet
	Name string `json:"name"`

	// StatusChannelId Unique identifier for the channel where the wallet status will be published
	StatusChannelId *openapi_types.UUID `json:"status_channel_id,omitempty"`

	// WalletOwnerAddress Wallet Contract Owner Address (42-character hex string starting with 0x)
	WalletOwnerAddress string `json:"wallet_owner_address"`

	// WalletType Type of the wallet
	WalletType CreateWalletWalletType `json:"wallet_type"`
}

// CreateWalletWalletType Type of the wallet
type CreateWalletWalletType string

// CreateWatcher defines model for CreateWatcher.
type CreateWatcher struct {
	union json.RawMessage
}

// CreateWatcherWithABI defines model for CreateWatcherWithABI.
type CreateWatcherWithABI struct {
	// Abi ABI definitions for the events to watch
	Abi []EventABI `json:"abi"`

	// Address Smart contract address to watch for events
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// Events List of event names to watch for
	Events []string `json:"events"`

	// Name Name for the watcher to help identify it
	Name *string `json:"name,omitempty"`
}

// CreateWatcherWithDomain defines model for CreateWatcherWithDomain.
type CreateWatcherWithDomain struct {
	// Address Smart contract address to watch for events
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// Domain Service domain namespace (e.g., "dvp", "dta")
	Domain string `json:"domain"`

	// Events List of event names to watch for within the domain
	Events []string `json:"events"`

	// Name Name for the watcher to help identify it
	Name *string `json:"name,omitempty"`
}

// Event defines model for Event.
type Event struct {
	Headers EventHeaders  `json:"headers"`
	Payload Event_Payload `json:"payload"`
}

// Event_Payload defines model for Event.Payload.
type Event_Payload struct {
	union json.RawMessage
}

// EventABI defines model for EventABI.
type EventABI struct {
	// Anonymous Whether the event is anonymous
	Anonymous bool `json:"anonymous"`

	// Inputs Event input parameters
	Inputs []EventABIInput `json:"inputs"`

	// Name Name of the event
	Name string `json:"name"`

	// Type Type must be 'event'
	Type EventABIType `json:"type"`
}

// EventABIType Type must be 'event'
type EventABIType string

// EventABIInput defines model for EventABIInput.
type EventABIInput struct {
	// Indexed Whether the parameter is indexed
	Indexed bool `json:"indexed"`

	// InternalType Internal Solidity type
	InternalType string `json:"internalType"`

	// Name Parameter name
	Name string `json:"name"`

	// Type Parameter type
	Type string `json:"type"`
}

// EventHeaders defines model for EventHeaders.
type EventHeaders struct {
	// Offset Unique offset for message ordering
	Offset int64                      `json:"offset"`
	Proofs []EventHeaders_Proofs_Item `json:"proofs"`

	// Type The type of event payload contained in this event
	Type EventHeadersType `json:"type"`
}

// EventHeadersProofs1 Generic proof object for future extensibility
type EventHeadersProofs1 map[string]interface{}

// EventHeaders_Proofs_Item defines model for EventHeaders.proofs.Item.
type EventHeaders_Proofs_Item struct {
	union json.RawMessage
}

// EventHeadersType The type of event payload contained in this event
type EventHeadersType string

// EventList defines model for EventList.
type EventList struct {
	Events []Event `json:"events"`

	// HasMore True if there are more events to fetch
	HasMore bool `json:"has_more"`
}

// EventTransaction defines model for EventTransaction.
type EventTransaction struct {
	// Hash Transaction hash
	Hash string `json:"hash"`

	// Timestamp Transaction timestamp
	Timestamp int64 `json:"timestamp"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// OCRProof defines model for OCRProof.
type OCRProof struct {
	// Alg Algorithm used for the proof
	Alg string `json:"alg"`

	// OcrContext OCR context data
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report data
	OcrReport string `json:"ocr_report"`

	// Signatures Array of signatures
	Signatures []string `json:"signatures"`
}

// Operation defines model for Operation.
type Operation struct {
	// Address Wallet address performing the operation
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the operation is executed
	ChainSelector string `json:"chain_selector"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt int64 `json:"created_at"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Status Current status of the operation
	Status string `json:"status"`

	// Transactions List of transactions to execute
	Transactions []TransactionRequest `json:"transactions"`

	// WalletOperationId Unique wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// OperationList defines model for OperationList.
type OperationList struct {
	Data []Operation `json:"data"`

	// HasMore True if there are more operations to fetch
	HasMore bool `json:"has_more"`
}

// OperationResponse defines model for OperationResponse.
type OperationResponse struct {
	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`
}

// OperationStatusPayload defines model for OperationStatusPayload.
type OperationStatusPayload struct {
	// Address Wallet address
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the operation will be executed
	ChainSelector string `json:"chain_selector"`

	// EventHash Deterministic event hash for verification (only present when status is confirmed)
	EventHash *string `json:"event_hash,omitempty"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signatures Array of DON node signatures for verification (only present when status is confirmed)
	Signatures *[]string `json:"signatures,omitempty"`

	// Status Current status of the operation
	Status OperationStatusPayloadStatus `json:"status"`

	// StatusReason Reason for the status
	StatusReason string                     `json:"status_reason"`
	Transaction  *EventTransaction          `json:"transaction,omitempty"`
	Type         OperationStatusPayloadType `json:"type"`

	// VerifiableEvent Base64 encoded verifiable event for verification (only present when status is confirmed)
	VerifiableEvent *string `json:"verifiable_event,omitempty"`

	// WalletOperationId Wallet operation identifier
	WalletOperationId string `json:"wallet_operation_id"`
}

// OperationStatusPayloadStatus Current status of the operation
type OperationStatusPayloadStatus string

// OperationStatusPayloadType defines model for OperationStatusPayload.Type.
type OperationStatusPayloadType string

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// UpdateChannel defines model for UpdateChannel.
type UpdateChannel struct {
	// Description New description for the channel
	Description string `json:"description"`

	// Name New name for the channel
	Name string `json:"name"`
}

// UpdateWallet defines model for UpdateWallet.
type UpdateWallet struct {
	// Name New name for the wallet
	Name string `json:"name"`
}

// UpdateWatcher defines model for UpdateWatcher.
type UpdateWatcher struct {
	// Name New name for the watcher
	Name string `json:"name"`
}

// Wallet defines model for Wallet.
type Wallet struct {
	// Address EVM wallet address
	Address string `json:"address"`

	// AllowedEcdsaSigners Allowed ECDSA public signing keys for the wallet
	AllowedEcdsaSigners []string `json:"allowed_ecdsa_signers"`

	// AllowedRsaSigners Allowed RSA public signing keys for the wallet
	AllowedRsaSigners []struct {
		// E RSA public exponent of allowed signer
		E string `json:"e"`

		// N RSA modulus of allowed signer
		N string `json:"n"`
	} `json:"allowed_rsa_signers"`

	// ChainSelector The chain selector to identify the chain where the wallet exists
	ChainSelector string `json:"chain_selector"`

	// CreatedAt Timestamp of when the wallet was created
	CreatedAt *int64 `json:"created_at,omitempty"`

	// Name Name of the wallet
	Name *string `json:"name,omitempty"`

	// Status Current status of the wallet
	Status string `json:"status"`

	// StatusChannelId Channel ID where wallet status events are published
	StatusChannelId *openapi_types.UUID `json:"status_channel_id,omitempty"`

	// WalletId Unique identifier for the wallet
	WalletId openapi_types.UUID `json:"wallet_id"`

	// WalletOwnerAddress Wallet Contract Owner Address
	WalletOwnerAddress string           `json:"wallet_owner_address"`
	WalletType         WalletWalletType `json:"wallet_type"`

	// WorkflowId Unique identifier for the workflow that created the wallet
	WorkflowId *string `json:"workflow_id,omitempty"`
}

// WalletWalletType defines model for Wallet.WalletType.
type WalletWalletType string

// WalletList defines model for WalletList.
type WalletList struct {
	Data []Wallet `json:"data"`

	// HasMore True if there are more wallets to fetch
	HasMore bool `json:"has_more"`
}

// WalletStatusPayload defines model for WalletStatusPayload.
type WalletStatusPayload struct {
	// Address EVM wallet address
	Address *string `json:"address,omitempty"`

	// ChainSelector The chain selector to identify the chain where the wallet exists
	ChainSelector string `json:"chain_selector"`

	// Status Current status of the wallet
	Status WalletStatusPayloadStatus `json:"status"`
	Type   WalletStatusPayloadType   `json:"type"`

	// WalletId Unique identifier for the wallet
	WalletId openapi_types.UUID `json:"wallet_id"`
}

// WalletStatusPayloadStatus Current status of the wallet
type WalletStatusPayloadStatus string

// WalletStatusPayloadType defines model for WalletStatusPayload.Type.
type WalletStatusPayloadType string

// Watcher defines model for Watcher.
type Watcher struct {
	// Abi ABI definitions for the events (if not using domain-based events)
	Abi *[]EventABI `json:"abi,omitempty"`

	// Address Smart contract address being watched
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// ChannelId ID of the channel this watcher belongs to
	ChannelId openapi_types.UUID `json:"channel_id"`

	// CreatedAt Timestamp of when the watcher was created
	CreatedAt int64 `json:"created_at"`

	// Domain Service domain namespace (if using domain-based events)
	Domain *string `json:"domain,omitempty"`

	// DonFamily DON family the watcher's workflow runs on (e.g., "zone-a"). Used to identify which DON nodes signed the events.
	DonFamily string `json:"don_family"`

	// Events List of event names being watched
	Events []string `json:"events"`

	// Name Name of the watcher for identification
	Name *string `json:"name,omitempty"`

	// Status Current status of the watcher
	Status string `json:"status"`

	// WatcherId Unique identifier for the watcher
	WatcherId openapi_types.UUID `json:"watcher_id"`

	// WorkflowId Unique identifier for the workflow that created the watcher
	WorkflowId string `json:"workflow_id"`
}

// WatcherEventPayload defines model for WatcherEventPayload.
type WatcherEventPayload struct {
	// Address Contract address that emitted the event
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// Domain Domain associated with the event (optional)
	Domain *string `json:"domain,omitempty"`

	// Name Name of the event
	Name string                  `json:"name"`
	Type WatcherEventPayloadType `json:"type"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`

	// WatcherId Unique watcher identifier
	WatcherId string `json:"watcher_id"`
}

// WatcherEventPayloadType defines model for WatcherEventPayload.Type.
type WatcherEventPayloadType string

// WatcherList defines model for WatcherList.
type WatcherList struct {
	Data []WatcherSummary `json:"data"`

	// HasMore True if there are more watchers to fetch
	HasMore bool `json:"has_more"`
}

// WatcherStatusPayload defines model for WatcherStatusPayload.
type WatcherStatusPayload struct {
	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// Status Current status of the watcher
	Status WatcherStatusPayloadStatus `json:"status"`

	// StatusCode Status code
	StatusCode string `json:"status_code"`

	// StatusReason Reason for the status
	StatusReason string                   `json:"status_reason"`
	Type         WatcherStatusPayloadType `json:"type"`

	// WatcherId Unique watcher identifier
	WatcherId string `json:"watcher_id"`
}

// WatcherStatusPayloadStatus Current status of the watcher
type WatcherStatusPayloadStatus string

// WatcherStatusPayloadType defines model for WatcherStatusPayload.Type.
type WatcherStatusPayloadType string

// WatcherSummary defines model for WatcherSummary.
type WatcherSummary struct {
	// Address Smart contract address being watched
	Address string `json:"address"`

	// ChainSelector The chain selector to identify the chain where the watcher will run
	ChainSelector string `json:"chain_selector"`

	// ChannelId ID of the channel this watcher belongs to
	ChannelId openapi_types.UUID `json:"channel_id"`

	// CreatedAt Timestamp of when the watcher was created
	CreatedAt int64 `json:"created_at"`

	// Domain Service domain namespace (if using domain-based events)
	Domain *string `json:"domain,omitempty"`

	// DonFamily DON family the watcher's workflow runs on (e.g., "zone-a"). Used to identify which DON nodes signed the events.
	DonFamily string `json:"don_family"`

	// Name Name of the watcher for identification
	Name *string `json:"name,omitempty"`

	// Status Current status of the watcher
	Status string `json:"status"`

	// WatcherId Unique identifier for the watcher
	WatcherId openapi_types.UUID `json:"watcher_id"`

	// WorkflowId Unique identifier for the workflow that created the watcher
	WorkflowId string `json:"workflow_id"`
}

// GetChannelsParams defines parameters for GetChannels.
type GetChannelsParams struct {
	// Name Filter channels by name (case-insensitive partial match)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Limit Maximum number of channels to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of channels to skip for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetChannelsChannelIdEventsParams defines parameters for GetChannelsChannelIdEvents.
type GetChannelsChannelIdEventsParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for message-oriented pagination. If not provided, the API returns the latest limit events ordered by descending offset.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetChannelsChannelIdEventsSearchParams defines parameters for GetChannelsChannelIdEventsSearch.
type GetChannelsChannelIdEventsSearchParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for message-oriented pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`

	// Type Filter events by type
	Type *GetChannelsChannelIdEventsSearchParamsType `form:"type,omitempty" json:"type,omitempty"`

	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// ChainSelector Filter by chain selector (applies to operation.status, watcher.status, watcher.event, and wallet.status types)
	ChainSelector *string `form:"chain_selector,omitempty" json:"chain_selector,omitempty"`

	// Status Filter by operation status (applies to operation.status), watcher status (applies to watcher.status), or wallet status (applies to wallet.status)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// WatcherId Filter by watcher ID (applies to watcher.status and watcher.event types)
	WatcherId *openapi_types.UUID `form:"watcher_id,omitempty" json:"watcher_id,omitempty"`

	// WalletId Filter by wallet ID (applies to wallet.status type)
	WalletId *openapi_types.UUID `form:"wallet_id,omitempty" json:"wallet_id,omitempty"`

	// Address Filter by wallet address (applies to operation.status and wallet.status types) or contract address (applies to watcher.event type)
	Address *string `form:"address,omitempty" json:"address,omitempty"`

	// WalletOperationId Filter by wallet operation ID (applies to operation.status type)
	WalletOperationId *string `form:"wallet_operation_id,omitempty" json:"wallet_operation_id,omitempty"`

	// OperationId Filter by operation ID (applies to operation.status type)
	OperationId *string `form:"operation_id,omitempty" json:"operation_id,omitempty"`

	// EventName Filter by event name (applies to watcher.event type)
	EventName *string `form:"event_name,omitempty" json:"event_name,omitempty"`

	// Domain Filter by watcher domain (applies to watcher.event type)
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`
}

// GetChannelsChannelIdEventsSearchParamsType defines parameters for GetChannelsChannelIdEventsSearch.
type GetChannelsChannelIdEventsSearchParamsType string

// GetChannelsChannelIdOperationsParams defines parameters for GetChannelsChannelIdOperations.
type GetChannelsChannelIdOperationsParams struct {
	// Limit Maximum number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of operations to skip for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`

	// Status Filter operations by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// ChainSelector Filter operations by chain selector
	ChainSelector *string `form:"chain_selector,omitempty" json:"chain_selector,omitempty"`

	// Address Filter operations by wallet address
	Address *string `form:"address,omitempty" json:"address,omitempty"`

	// WalletId Filter operations by wallet ID
	WalletId *openapi_types.UUID `form:"wallet_id,omitempty" json:"wallet_id,omitempty"`
}

// GetChannelsChannelIdWatchersParams defines parameters for GetChannelsChannelIdWatchers.
type GetChannelsChannelIdWatchersParams struct {
	// Limit Maximum number of watchers to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of watchers to skip for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`

	// Name Filter watchers by name (case-insensitive partial match)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Filter watchers by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// ChainSelector Filter watchers by chain selector
	ChainSelector *string `form:"chain_selector,omitempty" json:"chain_selector,omitempty"`

	// Address Filter watchers by contract address
	Address *string `form:"address,omitempty" json:"address,omitempty"`

	// Domain Filter watchers by domain
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`

	// EventName Filter watchers by event name
	EventName *string `form:"event_name,omitempty" json:"event_name,omitempty"`
}

// GetWalletsParams defines parameters for GetWallets.
type GetWalletsParams struct {
	// Name Filter wallets by name (case-insensitive partial match)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// ChainSelector Filter wallets by chain selector
	ChainSelector *string `form:"chain_selector,omitempty" json:"chain_selector,omitempty"`

	// Owner Filter wallets by owner address
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`

	// Type Filter wallets by type
	Type *GetWalletsParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Status Filter wallets by status
	Status *GetWalletsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Maximum number of wallets to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of wallets to skip for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetWalletsParamsType defines parameters for GetWallets.
type GetWalletsParamsType string

// GetWalletsParamsStatus defines parameters for GetWallets.
type GetWalletsParamsStatus string

// PostChannelsJSONRequestBody defines body for PostChannels for application/json ContentType.
type PostChannelsJSONRequestBody = CreateChannel

// PutChannelsChannelIdJSONRequestBody defines body for PutChannelsChannelId for application/json ContentType.
type PutChannelsChannelIdJSONRequestBody = UpdateChannel

// PostChannelsChannelIdOperationsJSONRequestBody defines body for PostChannelsChannelIdOperations for application/json ContentType.
type PostChannelsChannelIdOperationsJSONRequestBody = CreateOperation

// PostChannelsChannelIdWatchersJSONRequestBody defines body for PostChannelsChannelIdWatchers for application/json ContentType.
type PostChannelsChannelIdWatchersJSONRequestBody = CreateWatcher

// PatchChannelsChannelIdWatchersWatcherIdJSONRequestBody defines body for PatchChannelsChannelIdWatchersWatcherId for application/json ContentType.
type PatchChannelsChannelIdWatchersWatcherIdJSONRequestBody = UpdateWatcher

// PostWalletsJSONRequestBody defines body for PostWallets for application/json ContentType.
type PostWalletsJSONRequestBody = CreateWallet

// PatchWalletsWalletIdJSONRequestBody defines body for PatchWalletsWalletId for application/json ContentType.
type PatchWalletsWalletIdJSONRequestBody = UpdateWallet

// AsCreateWatcherWithDomain returns the union data inside the CreateWatcher as a CreateWatcherWithDomain
func (t CreateWatcher) AsCreateWatcherWithDomain() (CreateWatcherWithDomain, error) {
	var body CreateWatcherWithDomain
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateWatcherWithDomain overwrites any union data inside the CreateWatcher as the provided CreateWatcherWithDomain
func (t *CreateWatcher) FromCreateWatcherWithDomain(v CreateWatcherWithDomain) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateWatcherWithDomain performs a merge with any union data inside the CreateWatcher, using the provided CreateWatcherWithDomain
func (t *CreateWatcher) MergeCreateWatcherWithDomain(v CreateWatcherWithDomain) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateWatcherWithABI returns the union data inside the CreateWatcher as a CreateWatcherWithABI
func (t CreateWatcher) AsCreateWatcherWithABI() (CreateWatcherWithABI, error) {
	var body CreateWatcherWithABI
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateWatcherWithABI overwrites any union data inside the CreateWatcher as the provided CreateWatcherWithABI
func (t *CreateWatcher) FromCreateWatcherWithABI(v CreateWatcherWithABI) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateWatcherWithABI performs a merge with any union data inside the CreateWatcher, using the provided CreateWatcherWithABI
func (t *CreateWatcher) MergeCreateWatcherWithABI(v CreateWatcherWithABI) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateWatcher) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateWatcher) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOperationStatusPayload returns the union data inside the Event_Payload as a OperationStatusPayload
func (t Event_Payload) AsOperationStatusPayload() (OperationStatusPayload, error) {
	var body OperationStatusPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOperationStatusPayload overwrites any union data inside the Event_Payload as the provided OperationStatusPayload
func (t *Event_Payload) FromOperationStatusPayload(v OperationStatusPayload) error {
	v.Type = "operation.status"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOperationStatusPayload performs a merge with any union data inside the Event_Payload, using the provided OperationStatusPayload
func (t *Event_Payload) MergeOperationStatusPayload(v OperationStatusPayload) error {
	v.Type = "operation.status"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWatcherStatusPayload returns the union data inside the Event_Payload as a WatcherStatusPayload
func (t Event_Payload) AsWatcherStatusPayload() (WatcherStatusPayload, error) {
	var body WatcherStatusPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWatcherStatusPayload overwrites any union data inside the Event_Payload as the provided WatcherStatusPayload
func (t *Event_Payload) FromWatcherStatusPayload(v WatcherStatusPayload) error {
	v.Type = "watcher.status"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWatcherStatusPayload performs a merge with any union data inside the Event_Payload, using the provided WatcherStatusPayload
func (t *Event_Payload) MergeWatcherStatusPayload(v WatcherStatusPayload) error {
	v.Type = "watcher.status"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWatcherEventPayload returns the union data inside the Event_Payload as a WatcherEventPayload
func (t Event_Payload) AsWatcherEventPayload() (WatcherEventPayload, error) {
	var body WatcherEventPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWatcherEventPayload overwrites any union data inside the Event_Payload as the provided WatcherEventPayload
func (t *Event_Payload) FromWatcherEventPayload(v WatcherEventPayload) error {
	v.Type = "watcher.event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWatcherEventPayload performs a merge with any union data inside the Event_Payload, using the provided WatcherEventPayload
func (t *Event_Payload) MergeWatcherEventPayload(v WatcherEventPayload) error {
	v.Type = "watcher.event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWalletStatusPayload returns the union data inside the Event_Payload as a WalletStatusPayload
func (t Event_Payload) AsWalletStatusPayload() (WalletStatusPayload, error) {
	var body WalletStatusPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWalletStatusPayload overwrites any union data inside the Event_Payload as the provided WalletStatusPayload
func (t *Event_Payload) FromWalletStatusPayload(v WalletStatusPayload) error {
	v.Type = "wallet.status"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWalletStatusPayload performs a merge with any union data inside the Event_Payload, using the provided WalletStatusPayload
func (t *Event_Payload) MergeWalletStatusPayload(v WalletStatusPayload) error {
	v.Type = "wallet.status"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event_Payload) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event_Payload) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "operation.status":
		return t.AsOperationStatusPayload()
	case "wallet.status":
		return t.AsWalletStatusPayload()
	case "watcher.event":
		return t.AsWatcherEventPayload()
	case "watcher.status":
		return t.AsWatcherStatusPayload()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOCRProof returns the union data inside the EventHeaders_Proofs_Item as a OCRProof
func (t EventHeaders_Proofs_Item) AsOCRProof() (OCRProof, error) {
	var body OCRProof
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOCRProof overwrites any union data inside the EventHeaders_Proofs_Item as the provided OCRProof
func (t *EventHeaders_Proofs_Item) FromOCRProof(v OCRProof) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOCRProof performs a merge with any union data inside the EventHeaders_Proofs_Item, using the provided OCRProof
func (t *EventHeaders_Proofs_Item) MergeOCRProof(v OCRProof) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventHeadersProofs1 returns the union data inside the EventHeaders_Proofs_Item as a EventHeadersProofs1
func (t EventHeaders_Proofs_Item) AsEventHeadersProofs1() (EventHeadersProofs1, error) {
	var body EventHeadersProofs1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventHeadersProofs1 overwrites any union data inside the EventHeaders_Proofs_Item as the provided EventHeadersProofs1
func (t *EventHeaders_Proofs_Item) FromEventHeadersProofs1(v EventHeadersProofs1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventHeadersProofs1 performs a merge with any union data inside the EventHeaders_Proofs_Item, using the provided EventHeadersProofs1
func (t *EventHeaders_Proofs_Item) MergeEventHeadersProofs1(v EventHeadersProofs1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventHeaders_Proofs_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventHeaders_Proofs_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves channels for the organization.
	// (GET /channels)
	GetChannels(w http.ResponseWriter, r *http.Request, params GetChannelsParams)
	// Creates a new channel.
	// (POST /channels)
	PostChannels(w http.ResponseWriter, r *http.Request)
	// Deletes a channel.
	// (DELETE /channels/{channel_id})
	DeleteChannelsChannelId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID)
	// Retrieves a specific channel by ID.
	// (GET /channels/{channel_id})
	GetChannelsChannelId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID)
	// Updates a channel.
	// (PUT /channels/{channel_id})
	PutChannelsChannelId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID)
	// Retrieves events from a channel.
	// (GET /channels/{channel_id}/events)
	GetChannelsChannelIdEvents(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, params GetChannelsChannelIdEventsParams)
	// Query and search historical events from a channel.
	// (GET /channels/{channel_id}/events/search)
	GetChannelsChannelIdEventsSearch(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, params GetChannelsChannelIdEventsSearchParams)
	// Retrieves operations for a channel.
	// (GET /channels/{channel_id}/operations)
	GetChannelsChannelIdOperations(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, params GetChannelsChannelIdOperationsParams)
	// Sends a CreateOperation request to a channel.
	// (POST /channels/{channel_id}/operations)
	PostChannelsChannelIdOperations(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID)
	// Gets Operation record for a specific operation.
	// (GET /channels/{channel_id}/operations/{operation_id})
	GetChannelsChannelIdOperationsOperationId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, operationId openapi_types.UUID)
	// Retrieves watchers for a channel.
	// (GET /channels/{channel_id}/watchers)
	GetChannelsChannelIdWatchers(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, params GetChannelsChannelIdWatchersParams)
	// Creates a watcher in a channel.
	// (POST /channels/{channel_id}/watchers)
	PostChannelsChannelIdWatchers(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID)
	// Deletes a watcher.
	// (DELETE /channels/{channel_id}/watchers/{watcher_id})
	DeleteChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, watcherId openapi_types.UUID)
	// Retrieves a specific watcher by ID.
	// (GET /channels/{channel_id}/watchers/{watcher_id})
	GetChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, watcherId openapi_types.UUID)
	// Updates a watcher name.
	// (PATCH /channels/{channel_id}/watchers/{watcher_id})
	PatchChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request, channelId openapi_types.UUID, watcherId openapi_types.UUID)
	// Health check endpoint
	// (GET /health-check)
	GetHealthCheck(w http.ResponseWriter, r *http.Request)
	// Retrieves wallets for the organization.
	// (GET /wallets)
	GetWallets(w http.ResponseWriter, r *http.Request, params GetWalletsParams)
	// Creates a new wallet.
	// (POST /wallets)
	PostWallets(w http.ResponseWriter, r *http.Request)
	// Remove a wallet.
	// (DELETE /wallets/{wallet_id})
	DeleteWalletsWalletId(w http.ResponseWriter, r *http.Request, walletId openapi_types.UUID)
	// Retrieves a specific wallet by ID.
	// (GET /wallets/{wallet_id})
	GetWalletsWalletId(w http.ResponseWriter, r *http.Request, walletId openapi_types.UUID)
	// Updates a wallet name.
	// (PATCH /wallets/{wallet_id})
	PatchWalletsWalletId(w http.ResponseWriter, r *http.Request, walletId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetChannels operation middleware
func (siw *ServerInterfaceWrapper) GetChannels(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannels operation middleware
func (siw *ServerInterfaceWrapper) PostChannels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannelsChannelId operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelsChannelId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannelsChannelId(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelId(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutChannelsChannelId operation middleware
func (siw *ServerInterfaceWrapper) PutChannelsChannelId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutChannelsChannelId(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdEvents operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdEvents(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdEventsSearch operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdEventsSearch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdEventsSearchParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "chain_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_selector", r.URL.Query(), &params.ChainSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chain_selector", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "watcher_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "watcher_id", r.URL.Query(), &params.WatcherId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watcher_id", Err: err})
		return
	}

	// ------------- Optional query parameter "wallet_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "wallet_id", r.URL.Query(), &params.WalletId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_id", Err: err})
		return
	}

	// ------------- Optional query parameter "address" -------------

	err = runtime.BindQueryParameter("form", true, false, "address", r.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// ------------- Optional query parameter "wallet_operation_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "wallet_operation_id", r.URL.Query(), &params.WalletOperationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_operation_id", Err: err})
		return
	}

	// ------------- Optional query parameter "operation_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "operation_id", r.URL.Query(), &params.OperationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	// ------------- Optional query parameter "event_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "event_name", r.URL.Query(), &params.EventName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "event_name", Err: err})
		return
	}

	// ------------- Optional query parameter "domain" -------------

	err = runtime.BindQueryParameter("form", true, false, "domain", r.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdEventsSearch(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdOperations operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdOperations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdOperationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "chain_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_selector", r.URL.Query(), &params.ChainSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chain_selector", Err: err})
		return
	}

	// ------------- Optional query parameter "address" -------------

	err = runtime.BindQueryParameter("form", true, false, "address", r.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// ------------- Optional query parameter "wallet_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "wallet_id", r.URL.Query(), &params.WalletId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdOperations(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannelsChannelIdOperations operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsChannelIdOperations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannelsChannelIdOperations(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdOperationsOperationId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdOperationsOperationId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	// ------------- Path parameter "operation_id" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdOperationsOperationId(w, r, channelId, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdWatchers operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdWatchers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelsChannelIdWatchersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "chain_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_selector", r.URL.Query(), &params.ChainSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chain_selector", Err: err})
		return
	}

	// ------------- Optional query parameter "address" -------------

	err = runtime.BindQueryParameter("form", true, false, "address", r.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// ------------- Optional query parameter "domain" -------------

	err = runtime.BindQueryParameter("form", true, false, "domain", r.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	// ------------- Optional query parameter "event_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "event_name", r.URL.Query(), &params.EventName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "event_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdWatchers(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannelsChannelIdWatchers operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsChannelIdWatchers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannelsChannelIdWatchers(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannelsChannelIdWatchersWatcherId operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	// ------------- Path parameter "watcher_id" -------------
	var watcherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "watcher_id", r.PathValue("watcher_id"), &watcherId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watcher_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannelsChannelIdWatchersWatcherId(w, r, channelId, watcherId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelsChannelIdWatchersWatcherId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	// ------------- Path parameter "watcher_id" -------------
	var watcherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "watcher_id", r.PathValue("watcher_id"), &watcherId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watcher_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelsChannelIdWatchersWatcherId(w, r, channelId, watcherId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchChannelsChannelIdWatchersWatcherId operation middleware
func (siw *ServerInterfaceWrapper) PatchChannelsChannelIdWatchersWatcherId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channel_id" -------------
	var channelId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channel_id", r.PathValue("channel_id"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel_id", Err: err})
		return
	}

	// ------------- Path parameter "watcher_id" -------------
	var watcherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "watcher_id", r.PathValue("watcher_id"), &watcherId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watcher_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchChannelsChannelIdWatchersWatcherId(w, r, channelId, watcherId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWallets operation middleware
func (siw *ServerInterfaceWrapper) GetWallets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWalletsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "chain_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "chain_selector", r.URL.Query(), &params.ChainSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chain_selector", Err: err})
		return
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameter("form", true, false, "owner", r.URL.Query(), &params.Owner)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWallets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWallets operation middleware
func (siw *ServerInterfaceWrapper) PostWallets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWallets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWalletsWalletId operation middleware
func (siw *ServerInterfaceWrapper) DeleteWalletsWalletId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wallet_id" -------------
	var walletId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_id", r.PathValue("wallet_id"), &walletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWalletsWalletId(w, r, walletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWalletsWalletId operation middleware
func (siw *ServerInterfaceWrapper) GetWalletsWalletId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wallet_id" -------------
	var walletId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_id", r.PathValue("wallet_id"), &walletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWalletsWalletId(w, r, walletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchWalletsWalletId operation middleware
func (siw *ServerInterfaceWrapper) PatchWalletsWalletId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wallet_id" -------------
	var walletId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_id", r.PathValue("wallet_id"), &walletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wallet_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchWalletsWalletId(w, r, walletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/channels", wrapper.GetChannels)
	m.HandleFunc("POST "+options.BaseURL+"/channels", wrapper.PostChannels)
	m.HandleFunc("DELETE "+options.BaseURL+"/channels/{channel_id}", wrapper.DeleteChannelsChannelId)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}", wrapper.GetChannelsChannelId)
	m.HandleFunc("PUT "+options.BaseURL+"/channels/{channel_id}", wrapper.PutChannelsChannelId)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/events", wrapper.GetChannelsChannelIdEvents)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/events/search", wrapper.GetChannelsChannelIdEventsSearch)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/operations", wrapper.GetChannelsChannelIdOperations)
	m.HandleFunc("POST "+options.BaseURL+"/channels/{channel_id}/operations", wrapper.PostChannelsChannelIdOperations)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/operations/{operation_id}", wrapper.GetChannelsChannelIdOperationsOperationId)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/watchers", wrapper.GetChannelsChannelIdWatchers)
	m.HandleFunc("POST "+options.BaseURL+"/channels/{channel_id}/watchers", wrapper.PostChannelsChannelIdWatchers)
	m.HandleFunc("DELETE "+options.BaseURL+"/channels/{channel_id}/watchers/{watcher_id}", wrapper.DeleteChannelsChannelIdWatchersWatcherId)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{channel_id}/watchers/{watcher_id}", wrapper.GetChannelsChannelIdWatchersWatcherId)
	m.HandleFunc("PATCH "+options.BaseURL+"/channels/{channel_id}/watchers/{watcher_id}", wrapper.PatchChannelsChannelIdWatchersWatcherId)
	m.HandleFunc("GET "+options.BaseURL+"/health-check", wrapper.GetHealthCheck)
	m.HandleFunc("GET "+options.BaseURL+"/wallets", wrapper.GetWallets)
	m.HandleFunc("POST "+options.BaseURL+"/wallets", wrapper.PostWallets)
	m.HandleFunc("DELETE "+options.BaseURL+"/wallets/{wallet_id}", wrapper.DeleteWalletsWalletId)
	m.HandleFunc("GET "+options.BaseURL+"/wallets/{wallet_id}", wrapper.GetWalletsWalletId)
	m.HandleFunc("PATCH "+options.BaseURL+"/wallets/{wallet_id}", wrapper.PatchWalletsWalletId)

	return m
}
