// Code generated by cmd/gen-permissions from ./api/openapi.yaml. DO NOT EDIT.

package permissions

// RoutePermissions maps "METHOD <gin route pattern>" to the crec:* permissions
// the route requires; a caller must hold at least one of them (OR, not AND).
// Paths use gin's :id syntax, matching gin.Context.FullPath(), not OpenAPI's
// {id}.
var RoutePermissions = map[string][]string{
	"GET /channels":                                        {"crec:channel:read"},
	"GET /channels/:channel_id":                            {"crec:channel:read"},
	"GET /channels/:channel_id/events":                     {"crec:event:read"},
	"GET /channels/:channel_id/events/search":              {"crec:event:read"},
	"GET /channels/:channel_id/events/search/:event_id":    {"crec:event:read"},
	"GET /channels/:channel_id/operations":                 {"crec:operation:read"},
	"GET /channels/:channel_id/operations/:operation_id":   {"crec:operation:read"},
	"GET /channels/:channel_id/queries":                    {"crec:query:read"},
	"GET /channels/:channel_id/queries/:query_id":          {"crec:query:read"},
	"GET /channels/:channel_id/watchers":                   {"crec:watcher:read"},
	"GET /channels/:channel_id/watchers/:watcher_id":       {"crec:watcher:read"},
	"GET /networks":                                        {"crec:network:read"},
	"GET /wallets":                                         {"crec:wallet:read"},
	"GET /wallets/:wallet_id":                              {"crec:wallet:read"},
	"PATCH /channels/:channel_id":                          {"crec:channel:update", "crec:channel:archive"},
	"PATCH /channels/:channel_id/operations/:operation_id": {"crec:operation:sign"},
	"PATCH /channels/:channel_id/watchers/:watcher_id":     {"crec:watcher:update", "crec:watcher:archive"},
	"PATCH /wallets/:wallet_id":                            {"crec:wallet:update", "crec:wallet:archive"},
	"POST /channels":                                       {"crec:channel:create"},
	"POST /channels/:channel_id/operations":                {"crec:operation:create"},
	"POST /channels/:channel_id/queries":                   {"crec:query:create"},
	"POST /channels/:channel_id/watchers":                  {"crec:watcher:create"},
	"POST /wallets":                                        {"crec:wallet:create"},
}

// ExemptRoutes require no permission because they are served before an auth
// context exists.
var ExemptRoutes = map[string]struct{}{
	"GET /health-check": {},
}

// RequiredPermissions returns the permissions a route requires; the caller must
// hold at least one of them (OR, not AND). The second result is false when the
// route is exempt or unknown; callers must treat unknown routes as denied.
func RequiredPermissions(method, path string) ([]string, bool) {
	perms, ok := RoutePermissions[method+" "+path]
	return perms, ok
}

// IsExempt reports whether a route is exempt from permission checks.
func IsExempt(method, path string) bool {
	_, ok := ExemptRoutes[method+" "+path]
	return ok
}
