name: pull-request-main

on:
  pull_request:
    branches:
      - main
env:
  VACUUM_VERSION: "0.20.5"
jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: smartcontractkit/.github/actions/setup-golang@setup-golang/0.3.2
        with:
          go-version-file: ./go.mod
          use-go-cache: "true"
      - name: Download Vacuum
        run: |
          curl -L "https://github.com/daveshanley/vacuum/releases/download/v${VACUUM_VERSION}/vacuum_${VACUUM_VERSION}_linux_x86_64.tar.gz" \
            -o vacuum.tar.gz
          tar -xzf vacuum.tar.gz
          sudo mv vacuum /usr/local/bin/vacuum
      - name: Lint OpenAPI spec
        run: make validate-openapi

  generate:
    name: Verify Code Generation is Up-to-Date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: smartcontractkit/.github/actions/setup-golang@setup-golang/0.3.2
        with:
          go-version-file: ./go.mod
          use-go-cache: "true"

      - name: Install generation tools
        run: make tools

      - name: Run code generation
        run: make generate

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "Generated code is out of date. Run 'make generate' and commit the changes." && exit 1)

      - name: Go build
        run: go build ./...

  mod-tidy:
    name: Verify go.mod/go.sum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: smartcontractkit/.github/actions/setup-golang@setup-golang/0.3.2
        with:
          go-version-file: ./go.mod
          use-go-cache: "true"

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "go.mod or go.sum is not tidy. Run 'go mod tidy' and commit the changes." && exit 1)
