name: pull-request-main

on:
  pull_request:
    branches:
      - main
jobs:
  ci-lint:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
        actions: read
      steps:
        - name: install deps
          run: go install github.com/daveshanley/vacuum@latest
        - name: ci-lint
          run: make lint