// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package models

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OperationStatusDataStatus.
const (
	Broadcasting OperationStatusDataStatus = "broadcasting"
	Confirmed    OperationStatusDataStatus = "confirmed"
	Failed       OperationStatusDataStatus = "failed"
)

// EVMEvent defines model for EVMEvent.
type EVMEvent struct {
	// Address The contract address that emitted the event
	Address string `json:"address"`

	// BlockNumber The block number where the event was emitted
	BlockNumber uint64 `json:"block_number"`

	// BlockTimestamp The timestamp of the block where the event was emitted
	BlockTimestamp uint64 `json:"block_timestamp"`

	// ChainId The chain ID of the EVM network
	ChainId string `json:"chain_id"`

	// EventSignature The signature of the event
	EventSignature string `json:"event_signature"`

	// LogIndex The log index of the event in the transaction receipt
	LogIndex uint32                  `json:"log_index"`
	Params   *map[string]interface{} `json:"params,omitempty"`

	// TopicHash The topic hash of the event
	TopicHash string `json:"topic_hash"`

	// TxHash The transaction hash of the transaction that emitted the event
	TxHash string `json:"tx_hash"`
}

// OperationStatusData defines model for OperationStatusData.
type OperationStatusData struct {
	// Status Status of the operation (broadcasting, confirmed, failed).
	Status OperationStatusDataStatus `json:"status"`

	// StatusReason Reason for the status.
	StatusReason string `json:"status_reason"`

	// WalletAddress Wallet address associated with the operation
	WalletAddress string `json:"wallet_address"`

	// WalletOperationId Unique identifier for the wallet operation
	WalletOperationId string `json:"wallet_operation_id"`
}

// OperationStatusDataStatus Status of the operation (broadcasting, confirmed, failed).
type OperationStatusDataStatus string

// VerifiableEvent defines model for VerifiableEvent.
type VerifiableEvent struct {
	ChainEvent *VerifiableEvent_ChainEvent `json:"chain_event,omitempty"`

	// ChainFamily The blockchain family related to the event
	ChainFamily *string `json:"chain_family,omitempty"`

	// ChainSelector The specific blockchain network related to the event
	ChainSelector *string                 `json:"chain_selector,omitempty"`
	Data          *map[string]interface{} `json:"data,omitempty"`

	// Name The name of the event
	Name string `json:"name"`

	// Service The service that generated the event (_crec is used for internal events not related to a specific service)
	Service string `json:"service"`

	// Timestamp The timestamp when the event was created
	Timestamp time.Time `json:"timestamp"`
}

// VerifiableEvent_ChainEvent defines model for VerifiableEvent.ChainEvent.
type VerifiableEvent_ChainEvent struct {
	union json.RawMessage
}

// AsEVMEvent returns the union data inside the VerifiableEvent_ChainEvent as a EVMEvent
func (t VerifiableEvent_ChainEvent) AsEVMEvent() (EVMEvent, error) {
	var body EVMEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEVMEvent overwrites any union data inside the VerifiableEvent_ChainEvent as the provided EVMEvent
func (t *VerifiableEvent_ChainEvent) FromEVMEvent(v EVMEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEVMEvent performs a merge with any union data inside the VerifiableEvent_ChainEvent, using the provided EVMEvent
func (t *VerifiableEvent_ChainEvent) MergeEVMEvent(v EVMEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifiableEvent_ChainEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VerifiableEvent_ChainEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
