// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package models

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// EVMEvent defines model for EVMEvent.
type EVMEvent struct {
	// Address The contract address that emitted the event
	Address string `json:"address"`

	// BlockNumber The block number where the event was emitted
	BlockNumber uint64 `json:"block_number"`

	// BlockTimestamp The timestamp of the block where the event was emitted
	BlockTimestamp uint64 `json:"block_timestamp"`

	// ChainId The chain ID of the EVM network
	ChainId string `json:"chain_id"`

	// EventSignature The signature of the event
	EventSignature string `json:"event_signature"`

	// LogIndex The log index of the event in the transaction receipt
	LogIndex uint32                  `json:"log_index"`
	Params   *map[string]interface{} `json:"params,omitempty"`

	// TopicHash The topic hash of the event
	TopicHash string `json:"topic_hash"`

	// TxHash The transaction hash of the transaction that emitted the event
	TxHash string `json:"tx_hash"`
}

// VerifiableEvent defines model for VerifiableEvent.
type VerifiableEvent struct {
	// ChainFamily The blockchain family related to the event
	ChainFamily string `json:"chain_family"`

	// ChainSelector The specific blockchain network related to the event
	ChainSelector string                  `json:"chain_selector"`
	Data          *map[string]interface{} `json:"data,omitempty"`
	Event         VerifiableEvent_Event   `json:"event"`

	// Name The name of the event
	Name string `json:"name"`

	// Service The service that generated the event
	Service string `json:"service"`

	// Timestamp The timestamp when the event was created
	Timestamp time.Time `json:"timestamp"`
}

// VerifiableEvent_Event defines model for VerifiableEvent.Event.
type VerifiableEvent_Event struct {
	union json.RawMessage
}

// AsEVMEvent returns the union data inside the VerifiableEvent_Event as a EVMEvent
func (t VerifiableEvent_Event) AsEVMEvent() (EVMEvent, error) {
	var body EVMEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEVMEvent overwrites any union data inside the VerifiableEvent_Event as the provided EVMEvent
func (t *VerifiableEvent_Event) FromEVMEvent(v EVMEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEVMEvent performs a merge with any union data inside the VerifiableEvent_Event, using the provided EVMEvent
func (t *VerifiableEvent_Event) MergeEVMEvent(v EVMEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifiableEvent_Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VerifiableEvent_Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
